#!/usr/bin/env python3
"""Render reports/FOUNDER_READINESS_MATRIX.md from reports/FOUNDER_READINESS_MATRIX.json.

The JSON file is the single source of truth for the founder-readiness
reconciliation matrix. This script renders the Markdown view deterministically
from that JSON: same JSON in, same Markdown out, every time. Do not hand-edit
reports/FOUNDER_READINESS_MATRIX.md; edit the JSON and regenerate.

Usage:
    python scripts/generate_readiness_matrix.py            # write the .md
    python scripts/generate_readiness_matrix.py --check    # verify no drift
"""
from __future__ import annotations

import argparse
import difflib
import json
import re
from collections import Counter
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
JSON_PATH = ROOT / "reports" / "FOUNDER_READINESS_MATRIX.json"
MD_PATH = ROOT / "reports" / "FOUNDER_READINESS_MATRIX.md"

# Columns rendered in the full table, in order. status_history (an optional
# per-row audit trail the JSON may carry) is intentionally excluded: it is
# tolerated on input but never dumped into the table.
TABLE_COLUMNS: tuple[tuple[str, str], ...] = (
    ("req_id", "Req ID"),
    ("section", "Section"),
    ("text", "Requirement"),
    ("criticality", "Crit"),
    ("phase", "Phase"),
    ("status", "Status"),
    ("evidence_strength", "Evidence Strength"),
    ("implementation_evidence", "Implementation Evidence"),
    ("tests", "Tests"),
    ("ci_evidence", "CI Evidence"),
    ("later_authority", "Later Authority"),
    ("live_dependency", "Live Dependency"),
    ("gap_explanation", "Gap Explanation"),
    ("bucket", "Bucket"),
)

STATUS_ORDER = (
    "DONE",
    "PARTIAL",
    "MISSING",
    "INTENTIONALLY_DEFERRED",
    "REQUIRES_LIVE_INTEGRATION_OR_CREDENTIALS",
)
CRITICALITY_ORDER = ("P0", "P1", "P2", "P3", "P4")
BUCKET_ORDER = (
    "NONE",
    "FOUNDER_ENGINE_BLOCKER",
    "FOUNDER_WEB_INTEGRATION",
    "PRODUCTION_INFRASTRUCTURE",
    "LIVE_CONFIGURATION_OR_CREDENTIALS",
    "INTENTIONALLY_LATER",
)

BANNER = (
    "<!-- GENERATED BY scripts/generate_readiness_matrix.py from "
    "reports/FOUNDER_READINESS_MATRIX.json — DO NOT HAND-EDIT. "
    "Edit the JSON and run `python scripts/generate_readiness_matrix.py` "
    "to regenerate this file. -->"
)


def load_rows(path: Path = JSON_PATH) -> list[dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError(f"{path} must contain a JSON list of requirement rows")
    return data


def natural_phase_key(phase: str) -> tuple[int, str]:
    """Sort 'Phase 0' .. 'Phase 11' numerically, not lexically."""
    match = re.search(r"(\d+)", str(phase))
    if match:
        return (int(match.group(1)), str(phase))
    return (10**6, str(phase))


def escape_cell(value: Any) -> str:
    """Normalise a value for safe use as one Markdown table cell."""
    text = "" if value is None else str(value)
    text = text.replace("\r\n", " ").replace("\r", " ").replace("\n", " ")
    text = text.replace("|", "\\|")
    return " ".join(text.split())


def ordered_counts(counter: Counter[str], preferred: tuple[str, ...]) -> list[tuple[str, int]]:
    """Render a Counter's items with `preferred` values first (in that
    order), then any remaining keys the data actually contains, sorted."""
    result = [(key, counter[key]) for key in preferred if key in counter]
    extra = sorted(key for key in counter if key not in preferred)
    result.extend((key, counter[key]) for key in extra)
    return result


def render_count_block(title: str, counter: Counter[str], preferred: tuple[str, ...], total: int) -> list[str]:
    lines = [f"### {title} (Total = {total}):"]
    for key, count in ordered_counts(counter, preferred):
        pct = f" ({count / total:.1%})" if total else ""
        lines.append(f"- **`{key}`:** {count}{pct}")
    return lines


def render_criticality_breakdown(rows: list[dict[str, Any]]) -> list[str]:
    lines = ["### Criticality Counts (with status breakdown):"]
    by_crit: dict[str, Counter[str]] = {}
    for row in rows:
        by_crit.setdefault(row.get("criticality", ""), Counter())[row.get("status", "")] += 1
    crit_keys = [k for k in CRITICALITY_ORDER if k in by_crit] + sorted(
        k for k in by_crit if k not in CRITICALITY_ORDER
    )
    for crit in crit_keys:
        status_counts = by_crit[crit]
        crit_total = sum(status_counts.values())
        breakdown = ", ".join(
            f"{status}: {count}" for status, count in ordered_counts(status_counts, STATUS_ORDER)
        )
        lines.append(f"- **`{crit}`:** {crit_total} ({breakdown})")
    return lines


def render_phase_counts(rows: list[dict[str, Any]]) -> list[str]:
    counter: Counter[str] = Counter(row.get("phase", "") for row in rows)
    lines = [f"### Phase Counts (Total = {len(rows)}):"]
    for phase in sorted(counter, key=natural_phase_key):
        lines.append(f"- **`{phase}`:** {counter[phase]}")
    return lines


def render_table(rows: list[dict[str, Any]]) -> list[str]:
    header = "| " + " | ".join(label for _, label in TABLE_COLUMNS) + " |"
    divider = "| " + " | ".join(":---" for _ in TABLE_COLUMNS) + " |"
    lines = [header, divider]
    for row in rows:
        cells = [escape_cell(row.get(key, "")) for key, _ in TABLE_COLUMNS]
        lines.append("| " + " | ".join(cells) + " |")
    return lines


def render(rows: list[dict[str, Any]]) -> str:
    total = len(rows)
    status_counter: Counter[str] = Counter(row.get("status", "") for row in rows)
    bucket_counter: Counter[str] = Counter(row.get("bucket", "") for row in rows)

    sections: list[str] = [
        BANNER,
        "# OpportunityOS Founder-Readiness Reconciliation Matrix",
        "",
        "This document is generated. See the banner above; edit "
        "`reports/FOUNDER_READINESS_MATRIX.json` and regenerate instead of "
        "hand-editing this file.",
        "",
        f"**Source data:** `reports/FOUNDER_READINESS_MATRIX.json`  ",
        f"**Total Canonical Requirements Evaluated:** {total}  ",
        "",
        "---",
        "",
        "## 1. Summary Totals",
        "",
    ]
    sections.extend(render_count_block("Primary Status Counts", status_counter, STATUS_ORDER, total))
    sections.append("")
    sections.extend(render_criticality_breakdown(rows))
    sections.append("")
    sections.extend(render_phase_counts(rows))
    sections.append("")
    sections.extend(render_count_block("Work Bucket Counts", bucket_counter, BUCKET_ORDER, total))
    sections.append("")
    sections.append("---")
    sections.append("")
    sections.append("## 2. Exhaustive Canonical Requirements Matrix")
    sections.append("")
    sections.extend(render_table(rows))
    sections.append("")

    return "\n".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="render in memory and compare with the file on disk; never writes; "
        "exit 0 if identical, 1 if not",
    )
    args = parser.parse_args()

    rows = load_rows()
    rendered = render(rows)

    if args.check:
        existing = MD_PATH.read_text(encoding="utf-8") if MD_PATH.exists() else None
        if existing == rendered:
            print(f"{MD_PATH.relative_to(ROOT)} is up to date with {JSON_PATH.relative_to(ROOT)}.")
            return 0
        if existing is None:
            print(f"{MD_PATH.relative_to(ROOT)} does not exist. Run without --check to generate it.")
            return 1
        diff = difflib.unified_diff(
            existing.splitlines(keepends=True),
            rendered.splitlines(keepends=True),
            fromfile="on-disk",
            tofile="generated",
        )
        diff_lines = list(diff)
        print(f"{MD_PATH.relative_to(ROOT)} is stale relative to {JSON_PATH.relative_to(ROOT)}.")
        print(f"Diff has {len(diff_lines)} changed line(s). First 40 shown:")
        for line in diff_lines[:40]:
            print(line.rstrip("\n"))
        return 1

    MD_PATH.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote {MD_PATH.relative_to(ROOT)} from {len(rows)} rows in {JSON_PATH.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
