#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path


WORKFLOWS = ("Mandatory Governance & Test Suite", "State", "Guard", "Mirror")


def run(*command: str, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=cwd, text=True, capture_output=True, check=False)


def conclusions(repository: str, source_sha: str) -> dict[str, str]:
    response = run(
        "gh",
        "api",
        f"repos/{repository}/actions/runs?head_sha={source_sha}&per_page=100",
    )
    if response.returncode != 0:
        return {name: "unavailable" for name in WORKFLOWS}
    payload = json.loads(response.stdout)
    result: dict[str, str] = {}
    for workflow in WORKFLOWS:
        run_record = next(
            (item for item in payload.get("workflow_runs", []) if item.get("name") == workflow),
            None,
        )
        if run_record is None:
            result[workflow] = "missing"
        elif run_record.get("conclusion"):
            result[workflow] = str(run_record["conclusion"])
        else:
            result[workflow] = str(run_record.get("status") or "pending")
    return result


def latest_sync(mirror: Path) -> str:
    subject = run(
        "git", "log", "--format=%s", "--grep=^sync: ", "-1", cwd=mirror
    ).stdout.strip()
    return subject.removeprefix("sync: ").strip() if subject.startswith("sync: ") else "missing"


def compute_verdict(statuses: dict[str, str], mirror_current: bool) -> str:
    checks_green = all(statuses.get(name) == "success" for name in WORKFLOWS)
    if not checks_green:
        return "CHECKS FAILING"
    if not mirror_current:
        return "MIRROR STALE"
    return "HEALTHY"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repository", required=True)
    parser.add_argument("--source-sha", required=True)
    parser.add_argument("--source-subject", required=True)
    parser.add_argument("--mirror", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--wait-seconds", type=int, default=300)
    args = parser.parse_args()

    deadline = time.monotonic() + max(args.wait_seconds, 0)
    statuses = conclusions(args.repository, args.source_sha)
    while any(value in {"queued", "in_progress", "pending", "waiting", "requested"} for value in statuses.values()):
        if time.monotonic() >= deadline:
            break
        time.sleep(10)
        statuses = conclusions(args.repository, args.source_sha)

    run("git", "fetch", "origin", "main", cwd=args.mirror)
    run("git", "reset", "--hard", "origin/main", cwd=args.mirror)
    mirror_sha = latest_sync(args.mirror)
    mirror_current = args.source_sha.lower().startswith(mirror_sha.lower())
    verdict = compute_verdict(statuses, mirror_current)

    timestamp = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    content = f"""<!-- GENERATED BY heartbeat.yml — DO NOT EDIT -->
# OpportunityOS CI Status

- **Private main:** `{args.source_sha[:7]}` — {args.source_subject}
- **Checked:** {timestamp}
- **Mandatory Governance & Test Suite:** {statuses['Mandatory Governance & Test Suite']}
- **State:** {statuses['State']}
- **Guard:** {statuses['Guard']}
- **Mirror:** {statuses['Mirror']}
- **Mirror currency:** {'current' if mirror_current else 'stale'} — latest sync `{mirror_sha}`
- **Verdict:** {verdict}
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8", newline="\n")
    print(verdict)


if __name__ == "__main__":
    main()
